### ISSUE TITLE
How significant are these alphanumeric codes in the paper FP17?

### ISSUE THREAD

**Issue by pacharanero** [odonto/odonto#18]
The FP17 has single digit alphanumeric sublabels on each item:

![image](https://user-images.githubusercontent.com/2348385/36897689-7ed6e97c-1e0f-11e8-914c-ca00ce70f39c.png)

Questions for clinicians and also NHS BSA:

1) are these codes meaningful? (=do we need them in the data model?)
2) do they need to be displayed? (=do we add them to field labels?)
3) to the fields need to remain in the order they are in on this form (=do we need to re-layout the form)

**Comment by lamby** [comment]
AIUI these codes are references to a separate explanation document rather than being meaningful as symbols in themselves. I suspect that even if we include the documentation they "link" to, they are meaningful/useful to use as they would line-up with the original form.

**Comment by pacharanero** [comment]
thanks @lamby 

So possibly we could link to the relevant sections of the explanatory document using a more Webbish idiom eg:

![image](https://user-images.githubusercontent.com/2348385/36900430-29ab51de-1e1b-11e8-9771-7c043a5ff73f.png)

And ditch the letter/number codes

**Comment by lamby** [comment]
@pacharanero I think we should do both; provide the guidance inline/linked as you demo in your screenshot, but *somewhere* also include those reference numbers. Naturally, that could be hidden in the "guidance" link or something, but I think we should include it somewhere otherwise if/when someone using a paper form references "B" (or the way around) there is a canonical method of going from one to another.

**Comment by davidmiller** [comment]
This is unlikely to be the immediate priority - can re-open 'how to link to guidance inine' in response to user feedback perhaps...
